source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'devise'

gem 'homeland', path: '../../'
